### ISSUE TITLE
question about the data 

### ISSUE THREAD

**Issue by cai-yuxiang** [zhufq00/EventSkeletonGeneration#1]
hi, i have read your paper, and the result is amazing. but i am confused about the the input data file (.pkl), which appear in  `file_path = dir+'data/Wiki_IED_split/train/{}_train_pruned_new_no_iso_max_'.format(args.dataset) + str(args.max_n) + '_igraphs.pkl'` . can you release the cleaned data? thanks a lot

**Comment by zhufq00** [comment]
Sorry for late reply. Thank you for your attention to our work. You can obtain these files via the software(code) in this [paper](https://aclanthology.org/2022.naacl-main.147). If you need more help, feel free to contact me.

**Comment by cai-yuxiang** [comment]
thanks

**Comment by cai-yuxiang** [comment]
Hi, i feel confused about 

           `noise = (noisy_word - math.sqrt(alpha_t)*denoised_word)/math.sqrt(1-alpha_t) 

            if self.args.edge_loop:

                noisy_word = math.sqrt(alpha_tk)*edge_encoder_output + math.sqrt(1-alpha_tk)*noise 

            else:

                noisy_word = math.sqrt(alpha_tk)*denoised_word + math.sqrt(1-alpha_tk)*noise` 

which in `model/diffusion_model.py` , what is the detailed meaning about these code lines? thanks

**Comment by zhufq00** [comment]
Since you already solved the problem, I'm closing it here

**Comment by zjuermath** [comment]
I have read the paper mentioned above，but I found the repository is already closed，so is there any other ways to achieve the data？

**Comment by zhufq00** [comment]
You can find the code via this link: https://aclanthology.org/attachments/2022.naacl-main.147.software.zip

**Comment by zjuermath** [comment]
thanks a lot

**Comment by zhufq00** [comment]
if you need further help please feel free to email me with zhufangqi.hitsz@gmail.com, i'm open to
discuss further work under this paper

**Comment by zjuermath** [comment]
Excuse me，i found that there is something missing in the dir from the zip link，i didnt find the dir './data/'.

**Comment by zhufq00** [comment]
the original data can be downloaded via this link https://github.com/limanling/temporal-graph-schema

and need to be precessed via the zip code to become the curated data in the paper Doublegae.

**Comment by zjuermath** [comment]
thanks a lot，i will try it
