### ISSUE TITLE
Questions about metrics and implement details

### ISSUE THREAD

**Issue by cai-yuxiang** [zhufq00/EventSkeletonGeneration#2]
你好，作者，

我关注到论文中提到“We select the best checkpoint, and the best performing schema on the validation set according to the event type match (F1) metric”，那对应输出评估结果“Ours avg”应该是哪一部分代码，对应输出评估结果“Ours”应该是哪一部分代码？以下代码存在缩进问题请见谅！

(1)
` 
logger.info('---------------------------------------')
logger.info('test_mbr_etm_F1={:.4f}'.format(test_etm_list[mbr_index]))
logger.info('test_mbr_esm2_F1={:.4f}'.format(test_esm2_list[mbr_index]))
logger.info('test_mbr_esm3_F1={:.4f}'.format(test_esm3_list[mbr_index]))
logger.info('---------------------------------------')
`
(2)
` 
logger.info('---------------------------------------')
dev_etm_max_index = dev_etm_list.index(max(dev_etm_list))
  logger.info('dev_etm_best_etm_F1={:.4f}'.format(dev_etm_list[dev_etm_max_index]))
  logger.info('dev_etm_best_esm2_F1={:.4f}'.format(dev_esm2_list[dev_etm_max_index]))
  logger.info('dev_etm_best_esm3_F1={:.4f}'.format(dev_esm3_list[dev_etm_max_index]))
  logger.info('test_etm_best_etm_F1={:.4f}'.format(test_etm_list[dev_etm_max_index]))
  logger.info('test_etm_best_esm2_F1={:.4f}'.format(test_esm2_list[dev_etm_max_index]))
  logger.info('test_etm_best_esm3_F1={:.4f}'.format(test_esm3_list[dev_etm_max_index]))
`
(3)
`
logger.info('---------------------------------------')
            dev_esm3_max_index = dev_esm3_list.index(max(dev_esm3_list))
            logger.info('dev_esm3_best_etm_F1={:.4f}'.format(dev_etm_list[dev_esm3_max_index]))
            logger.info('dev_esm3_best_esm2_F1={:.4f}'.format(dev_esm2_list[dev_esm3_max_index]))
            logger.info('dev_esm3_best_esm3_F1={:.4f}'.format(dev_esm3_list[dev_esm3_max_index]))
            logger.info('test_esm3_best_etm_F1={:.4f}'.format(test_etm_list[dev_esm3_max_index]))
            logger.info('test_esm3_best_esm2_F1={:.4f}'.format(test_esm2_list[dev_esm3_max_index]))
            logger.info('test_esm3_best_esm3_F1={:.4f}'.format(test_esm3_list[dev_esm3_max_index]))
`
(4)
`
dev_performance_sum_list = []
            for i in range(len(dev_etm_list)):
                if args.dataset=='wiki_mass_car_bombings':
                    _sum = dev_etm_list[i] + dev_esm2_list[i] + dev_esm3_list[i] # 2 1 0.8
                elif args.dataset=='suicide_ied':
                    _sum = dev_etm_list[i] + dev_esm2_list[i] + dev_esm3_list[i] # 1 0.5 1
                elif args.dataset=='wiki_ied_bombings':
                    _sum = dev_etm_list[i] + dev_esm2_list[i] + dev_esm3_list[i] # 1.05 1 1 
                dev_performance_sum_list.append(_sum)
            best_dev_index = dev_performance_sum_list.index(max(dev_performance_sum_list))
            logger.info('---------------------------------------')
            logger.info('best_dev_index={}'.format(best_dev_index))
            logger.info('dev_best_dev_index_etm_F1={:.4f}'.format(dev_etm_list[best_dev_index]))
            logger.info('dev_best_dev_index_esm2_F1={:.4f}'.format(dev_esm2_list[best_dev_index]))
            logger.info('dev_best_dev_index_esm3_F1={:.4f}'.format(dev_esm3_list[best_dev_index]))
            logger.info('test_best_dev_index_etm_F1={:.4f}'.format(test_etm_list[best_dev_index]))
            logger.info('test_best_dev_index_esm2_F1={:.4f}'.format(test_esm2_list[best_dev_index]))
            logger.info('test_best_dev_index_esm3_F1={:.4f}'.format(test_esm3_list[best_dev_index]))
            logger.info('---------------------------------------')
`
祝好

**Comment by zhufq00** [comment]
Since we have discussed this issue privately, I am closing it here
